### ISSUE TITLE
Subtitles not Added due to "Culture not found" Error

### ISSUE THREAD

**Issue by Ithiloneth** [azam/jellyfin-plugin-localsubs#2]
My Jellyfin (latest), ran it's scans as usual last night and the Subtitle scan took much longer than normal - good sign I think!

However, there seem to not have been any subtitles added, and my log is full errors like this one:

```
[2023-06-12 01:21:50.446 +00:00] [ERR] [44] Jellyfin.Plugin.LocalSubs.LocalSubsProvider: Culture not found for "en"
System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(String name)
```

It seems to me the plugin found the subtitles, but could not add them because it's trying to add them with a localization tag that's not supported? I'm not sure.

Hope this can be fixed - the plugin would make a big difference for my collection!

**Comment by Ithiloneth** [comment]
@azam
Thank you for replying!

Movie path:
X:\HL_Drop\Public\Video\Movie\Movie.2000.1080p.BluRay.x265\Movie.2002.1080p.BluRay.x265.mp4
X:\HL_Drop\Public\Video\Movie\Movie.2000.1080p.BluRay.x265\Subs\nn_Language.srt

TV path:
X:\HL_Drop\Public\Video\TV\Show.S01.1080p.BluRay.x265\Show.S01E01.1080p.BluRay.x265.mp4
X:\HL_Drop\Public\Video\TV\Show.S01.1080p.BluRay.x265\Subs\Show.S01E01.1080p.BluRay.x265\n_Language.srt

The language is in long form: I.E "English".
For shows, there is a folder "Subs" and in that folder are individual folders for each episode, named after that episode, and these folders contain the actual subtitles which are not named after the episode - just the language.

Library subtitle languages are:
English, Japanese, Swedish

Not all media actually _has_ subtitles in all three, or even any, language.

**Comment by azam** [comment]
@Ithiloneth 
Thank you for the info!

I can see nothing wrong with your configuration (almost same as mine), and it is most probably an environment issue.

.NET uses system installed globalization data (data from ICU) for enumerating languages and this plugin uses the API on .NET standard library to get those data.

Specifically for each subtitle language set at the library, it will try to match for 2-letter code (`en` for English, `se` for Swedish), 3-letter code (`eng` for English, `swe` for Swedish) and the English name (`English` for English, `Swedish` for Swedish) on the `%l%` placeholder when scanning for subtitle files.

These language codes and its english names are matched against that globalization data (ICU data) and it must exist on your system, and for Linux, it is using the ICU library for that.

You can try these steps:

* Make sure ICU library and data is installed
  * Debian derivatives:
    `sudo apt install libicu-devel`
  * Alpine:
    `apk add icu-libs icu-data-full`
* If you are building your own Docker image, make sure ICU is installed as above, and also make sure `ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true` is not defined on your Dockerfile.
* Make sure `System.Globalization.Invariant` is not set to `true`, or is not defined on `jellyfin.runtimeconfig.json` (default should be `false` when undefined on runtimeconfig). This setting disables references to globalization data if set to `true`.

**Comment by Ithiloneth** [comment]
@azam 
Thank you for your reply.

I don't understand how to do the last step:
`Make sure System.Globalization.Invariant is not set to true, or is not defined on jellyfin.runtimeconfig.json (default should be false when undefined on runtimeconfig). This setting disables references to globalization data if set to true.`

Am I looking for a .json file that I need to edit? Might you know what directory to look in?

My container image is not custom and I'm hesitant to try the library installations before I confirm if this can be fixed with a simple config edit.

**Comment by azam** [comment]
@Ithiloneth 
Cool! I hope it works for you.
`jellyfin.runtimeconfig.json` should directly be on your jellyfin installation directory (you would need to have a custom Dockerfile if you want to modify this).
I don't think this is something I can resolve from plugin-side, because it is part of the .NET runtime environment configuration.

**Comment by Ithiloneth** [comment]
The issue was resolved by changing the System.Globalization.Invariant variable.
It was found in the GUI for Docker on DSM 7.

I've tried to make my posts clear for those who run into the same issue and are looking for a fix - feel free to reach out to me if you have the same issue for Jellyfin when run in Docker on Synology 7 or later.

Thank you azam for your help and for the awesome plugin!

**Comment by azam** [comment]
@Ithiloneth 
Glad it worked for you. Really appreciate the details!
